name: Setup MKXP-Z
description: 'Set Up MKXP-Z on this runner'

inputs:
  mkxpz-version:
    required: true
    type: string
  token:
    require: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create Fake Audio Device
      uses: LABSN/sound-ci-helpers@v1

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Ruby Gem Setup Credentials
      shell: bash
      run: gem sources --add  https://${{ github.event.pusher.name }}:${{ inputs.token }}@rubygems.pkg.github.com/fcorso2016/

    - name: Install MKXP-Z
      shell: bash
      run: gem install mkxp-z --version "${{ inputs.mkxpz-version }}"