name: Setup MKXP-Z
on:
  push:
    branches:
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  setup-mkxp-z:
    name: Sound Test
    runs-on: ubuntu-22.04
    steps:
      - name: Create Fake Audio Device
        uses: LABSN/sound-ci-helpers@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1