name: Setup MKXP-Z
on:
  push:
    branches:
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  setup-mkxp-z:
    name: Setup MKXP-Z
    runs-on: ubuntu-22.04
    steps:
      - name: Create Fake Audio Device
        uses: LABSN/sound-ci-helpers@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Ruby Gem Setup Credentials
        run: gem sources --add  https://${{ github.event.pusher.name }}:${{ secrets.GITHUB_TOKEN }}@rubygems.pkg.github.com/fcorso2016/

      - name: Install MKXP-Z
        run:
          gem install mkxp-z --version "2.4.2.linux"