name: Setup MKXP-Z
on:
  push:
    branches:
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  setup-mkxp-z:
    name: Setup MKXP-Z
    runs-on: ubuntu-22.04
    steps:
      - name: Create Fake Audio Device
        uses: LABSN/sound-ci-helpers@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Ruby Gem Setup Credentials
        uses: fac/ruby-gem-setup-credentials-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install MKXP-Z
        run:
          gem install mkxp-z --version "2.4.2.linux"