# I have no idea what I'm doing
name: Test Reusable Workflow

on:
  push:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]
  pull_request:
    branches: [ 'dev', 'autobuild' ]
    paths-ignore: [ '*.md', '*.json', '*.png' ]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: |
            .github
            tests
            Rakefile

      - name: Set Up MKXP-Z
        uses: ./.github/actions/mkxp-z
        with:
          mkxpz-version: 2.4.2.win32.d2f4ecd
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Gem
        run:
          rake

  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: |
            .github
            tests
            Rakefile

      - name: Set Up MKXP-Z
        uses: ./.github/actions/mkxp-z
        with:
          mkxpz-version: 2.4.2.linux.d2f4ecd
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Gem
        run:
          rake

  docker:
    name: Docker
    runs-on: ubuntu-22.04
    container: ghcr.io/fcorso2016/mkxp-z:latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: |
            .github
            tests
            Rakefile
            setup_sound.sh

      - name: Create Fake Audio Device
        shell: bash
        run: |
          source setup_sound.sh

      - name: Test Gem
        run:
          rake